### ISSUE TITLE
Finish Indication Board Software

### ISSUE THREAD

**Issue by davidlenfesty** [UofA-SPEAR/embedded#15]
Really simple, just needs to PWM the RGB lines based on some state published over CAN bus.

Collaborate with software to determine the message type, and what exactly needs to be done.

Needs to conform to URC rules, however we can likely add some extra features, such as it flashes colours on state transitions. Talk with software about what they would like to see.

**Comment by rpshukla** [comment]
From jira:
Jarrett Yu
25 July 2020, 14:29

Working with pwm drivers on chibios

**Comment by JackOpgenorth** [comment]
Closing this as part of cleanup, not doing this anymore
