### ISSUE TITLE
Motor Controller Code cleanup

### ISSUE THREAD

**Issue by davidlenfesty** [UofA-SPEAR/embedded#21]
It's kind of in a weird half-state right now.

- [ ] Migrate fully to Kernel C style
- [ ] Rename functions so everything has a consistent scheme
- [ ] Move motor functions into it's own source file
- [ ] Improve interface between main, motors, and encoders, it's kind of scattered right now. Having a single interface would be better.

Anything else you can think of.

**Comment by davidlenfesty** [comment]
Most of these are mostly applicable, bumping post-competition.

**Comment by JackOpgenorth** [comment]
Closing this as part of cleaning, most of the motor controller code is being rewritten by Minh
