### ISSUE TITLE
Power Rail Monitoring

### ISSUE THREAD

**Issue by davidlenfesty** [UofA-SPEAR/embedded#22]
Once the computer subsystem PDU is designed, it will need to have a Speedy on it to monitor power rails status (voltage, current, faults).

Exactly what that interface will look like is unknown at the moment.

**Comment by davidlenfesty** [comment]
It will need to publish to the message type uavcan.equipment.power.CircuitStatus.

**Comment by JackOpgenorth** [comment]
Closing this as part of cleanup
