### ISSUE TITLE
UAVCAN v1 Parameters

### ISSUE THREAD

**Issue by davidlenfesty** [UofA-SPEAR/embedded#31]
This needs to be implemented both on the interface side, and by adding some code infrastructure to make parameters easy.

Since it's C, lots of boilerplate for each parameter is fine, just make it reasonable to add/remove parameters, and some method of versioning so that we can detect when the list of parameters have changed.

**Comment by JackOpgenorth** [comment]
Closing since we are no longer migrating to v1
