### ISSUE TITLE
Create unified libcanard interface (in C++?)

### ISSUE THREAD

**Issue by mayshukla** [UofA-SPEAR/embedded#43]
We need to have a single libcanard wrapper that is stored outside of each project so that we aren't copying code around, and to have a nice, easy-to-understand interface.

**Comment by rpshukla** [comment]
From jira:
David Lenfesty
20 August 2020, 20:04

Simply needs more testing on boards before we call it done.

**Comment by JackOpgenorth** [comment]
Closing since we are no longer migrating to v1
