### ISSUE TITLE
Add actuator/Command support to controllers

### ISSUE THREAD

**Issue by davidlenfesty** [UofA-SPEAR/embedded#9]
As of now, they only support ArrayCommands. It would make sense to also support single Commands.

**Comment by pavel-kirienko** [comment]
Hi folks, you should consider migrating to UAVCAN v1.0 -- the first stable release of the protocol, where some design issues have been resolved. Context:

- https://new.uavcan.org
- https://forum.uavcan.org/t/stockholm-summit-recap/170

**Comment by davidlenfesty** [comment]
Good point for sure. I have been planning on it once libcanard fully supports it (i.e. there's a release). Referenced in issue #10 

For now though in our specific use case single Commands is still useful.
